export const DU_COLLEGES = [
  "Acharya Narendra Dev College",
  "Aditi Mahavidyalaya",
  "Aryabhatta College",
  "Atma Ram Sanatan Dharma College",
  "Bhagini Nivedita College",
  "Bharati College",
  "College of Vocational Studies",
  "Daulat Ram College",
  "Deen Dayal Upadhyaya College",
  "Delhi College of Arts & Commerce",
  "Deshbandhu College",
  "Dyal Singh College",
  "Gargi College",
  "Hansraj College",
  "Hindu College",
  "Indraprastha College for Women",
  "Institute of Home Economics",
  "Janki Devi Memorial College",
  "Jesus & Mary College",
  "Kalindi College",
  "Kamala Nehru College",
  "Kirori Mal College",
  "Lady Irwin College",
  "Lady Shri Ram College for Women",
  "Lakshmibai College",
  "Maharaja Agrasen College",
  "Maitreyi College",
  "Mata Sundri College for Women",
  "Miranda House",
  "Moti Lal Nehru College",
  "PGDAV College",
  "Ramanujan College",
  "Ram Lal Anand College",
  "Ramjas College",
  "Satyawati College",
  "Shaheed Bhagat Singh College",
  "Shaheed Rajguru College of Applied Sciences",
  "Shaheed Sukhdev College of Business Studies",
  "Shivaji College",
  "Shyam Lal College",
  "Sri Aurobindo College",
  "Sri Aurobindo College (Evening)",
  "Sri Guru Gobind Singh College of Commerce",
  "Sri Guru Nanak Dev Khalsa College",
  "Sri Venkateswara College",
  "St. Stephen's College",
  "Swami Shraddhanand College",
  "Vivekananda College",
];

export const DU_COURSES = [
  "B.A. Programme",
  "B.A. (Hons) English",
  "B.A. (Hons) Political Science",
  "B.A. (Hons) Psychology",
  "B.A. (Hons) History",
  "B.A. (Hons) Economics",
  "B.A. (Hons) Sociology",
  "B.Com.",
  "B.Com. (Hons)",
  "B.Sc. (Hons) Computer Science",
  "B.Sc. (Hons) Mathematics",
  "B.Sc. (Hons) Physics",
  "B.Sc. (Hons) Chemistry",
  "B.Sc. (Hons) Botany",
  "B.Sc. (Hons) Zoology",
  "BMS (Bachelor of Management Studies)",
  "BBA (FIA)",
  "B.A. (Hons) Business Economics",
  "B.El.Ed.",
  "B.Tech. (IT & Mathematical Innovations)",
];

export const YEAR_OPTIONS = ['1st Year','2nd Year','3rd Year','4th Year'];

export const INTERESTS = [
  { label: "Music", value: "music", emoji: "🎵" },
  { label: "Dance", value: "dance", emoji: "💃" },
  { label: "Tech", value: "tech", emoji: "💻" },
  { label: "Photography", value: "photography", emoji: "📸" },
  { label: "Videography", value: "videography", emoji: "🎥" },
  { label: "Sports", value: "sports", emoji: "⚽" },
  { label: "Fitness", value: "fitness", emoji: "🏋️" },
  { label: "Acting", value: "acting", emoji: "🎭" },
  { label: "Reading", value: "reading", emoji: "📚" },
  { label: "Gaming", value: "gaming", emoji: "🎮" },
  { label: "Content Creation", value: "content_creation", emoji: "✨" },
];

export const SKILLS = [
  { label: "Video Editing", value: "video_editing", emoji: "🎬" },
  { label: "Graphic Design", value: "graphic_design", emoji: "🎨" },
  { label: "UI/UX", value: "ui_ux", emoji: "🖌️" },
  { label: "Python", value: "python", emoji: "🐍" },
  { label: "JavaScript", value: "javascript", emoji: "⚡" },
  { label: "Public Speaking", value: "public_speaking", emoji: "🎤" },
  { label: "Leadership", value: "leadership", emoji: "🧠" },
  { label: "Marketing", value: "marketing", emoji: "📈" },
  { label: "Event Planning", value: "event_planning", emoji: "🗓️" },
];
